import type { Metadata } from "next";
import { Just_Me_Again_Down_Here } from "next/font/google";
import "./globals.css";
import Header from '@/components/header';
import Footer from '@/components/footer';
import { AntdRegistry } from '@ant-design/nextjs-registry';

const jmadh = Just_Me_Again_Down_Here({ weight: '400', subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={jmadh.className}>
        <AntdRegistry>
          <Header />
          {children}
          <Footer />
        </AntdRegistry>
      </body>
    </html>
  );
}
